const HOUSE_NAMES=["Yellow House","Blue House","Red House","Green House"];
const $=id=>document.getElementById(id);let results=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function totalFor(h,rows=results){return rows.filter(r=>r.house===h).reduce((s,r)=>s+Number(r.points||0),0);}
function normalized(r){return {...r,regNo:r.regNo??r.reg_no??"",createdAt:r.createdAt??r.created_at??""};}
async function loadResults(){const {data,error}=await supabaseClient.from("points").select("*")
.order("createdAt", { ascending: false });
if(error)throw error;results=(data||[])
    .map(normalized);renderAll();}
function renderDashboard(){const rows=results,total=rows.reduce((s,r)=>s+Number(r.points||0),0);if($("stats"))$("stats").innerHTML=`<article class="stat"><span>Recorded Results</span><strong>${rows.length}</strong></article><article class="stat"><span>Total Points Awarded</span><strong>${total}</strong></article><article class="stat"><span>Houses</span><strong>4</strong></article>`;if($("houses")){$("houses").innerHTML=HOUSE_NAMES.map((h,i)=>`<button class="house-card house-${i}" data-house="${h}"><span>${h}</span><strong>${totalFor(h)} <small>pts</small></strong><em>View participants →</em></button>`).join("");$("houses").querySelectorAll("[data-house]").forEach(b=>b.addEventListener("click",()=>showHouse(b.dataset.house)));}if($("recentRows"))$("recentRows").innerHTML=rows.slice(0,8).map(r=>`<tr><td>${esc(r.date||"—")}</td><td>${esc(r.event)}</td><td>${esc(r.house)}</td><td>${esc(r.participant)}</td><td>${esc(r.rank)}</td><td>${esc(r.points)}</td></tr>`).join("")||'<tr><td colspan="6">No results recorded yet.</td></tr>';}
function showHouse(h){const s=$("houseDetails");if(!s)return;const rows=results.filter(r=>r.house===h),people={};rows.forEach(r=>{let p=people[r.participant]??={name:r.participant,regNo:r.regNo,points:0,events:[]};p.points+=Number(r.points||0);p.events.push(r.event);});s.innerHTML=`<h2>${esc(h)} — Participant Points</h2><div class="table-wrap"><table><thead><tr><th>Participant</th><th>Register No.</th><th>Events</th><th>Total Points</th></tr></thead><tbody>${Object.values(people).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.regNo||"—")}</td><td>${esc(p.events.join(", "))}</td><td>${p.points}</td></tr>`).join("")||'<tr><td colspan="4">No participants recorded.</td></tr>'}</tbody></table></div>`;}
function renderAdmin(){const body=$("adminRows");if(!body)return;body.innerHTML=results.map(r=>`<tr><td>${esc(r.date||"—")}</td><td>${esc(r.event)}</td><td>${esc(r.house)}</td><td>${esc(r.participant)}</td><td>${esc(r.regNo||"—")}</td><td>${esc(r.rank)}</td><td>${esc(r.points)}</td><td><button class="btn tiny" data-edit="${r.id}">Edit</button> <button class="btn tiny danger" data-delete="${r.id}">Delete</button></td></tr>`).join("");$("emptyAdmin").textContent=results.length?"":"No results added yet.";body.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editResult(b.dataset.edit)));body.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>deleteResult(b.dataset.delete)));}
function renderAll(){renderDashboard();renderAdmin();}
function clearForm(){if(!$("resultForm"))return;$("resultForm").reset();$("resultId").value="";$("formTitle").textContent="Add Result";}
function editResult(id){const r=results.find(x=>x.id===id);if(!r)return;$("resultId").value=r.id;$("eventChoice").value=r.event;["house","participant","regNo","rank","points","date","remarks"].forEach(k=>$(k).value=r[k]??"");$("formTitle").textContent="Edit Result";window.scrollTo({top:0,behavior:"smooth"});}
async function deleteResult(id){if(!confirm("Delete this result?"))return;const {error}=await supabaseClient.from("points").delete().eq("id",id);if(error){alert(error.message);return;}await loadResults();}
document.addEventListener("DOMContentLoaded",async()=>{try{await loadResults();}catch(e){console.error(e);if($("adminMessage"))$("adminMessage").textContent="Could not load data. Check Supabase URL, key, table and RLS policies.";return;}
const form=$("resultForm");if(form)form.addEventListener("submit",async e=>{e.preventDefault();const id=$("resultId").value;const item={event:$("eventChoice").value.trim(),house:$("house").value,participant:$("participant").value.trim(),regNo:$("regNo").value.trim(),rank:$("rank").value,points:Number($("points").value),date:$("date").value||null,remarks:$("remarks").value.trim()};let q=id?supabaseClient.from("points").update(item).eq("id",id):supabaseClient.from("points").insert(item);const {error}=await q;if(error){$("adminMessage").textContent=error.message;return;}$("adminMessage").textContent="Saved successfully.";clearForm();await loadResults();});
$("cancelEdit")?.addEventListener("click",clearForm);$("exportCsv")?.addEventListener("click",()=>{const fields=["date","event","house","participant","regNo","rank","points","remarks"];const csv=[fields.join(","),...results.map(r=>fields.map(k=>'"'+String(r[k]??"").replace(/"/g,'""')+'"').join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"}));a.download="vibranza-house-points.csv";a.click();URL.revokeObjectURL(a.href);});
});
